- name: install, start & enable the nginx server
  hosts: web
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start the service
      ansible.builtin.service: # service in ansible is equivalent to systemctl CMD in shell
        name: nginx
        state: started